export const projects = [
  {
    id: "viewer",
    name: "産連調査Viewer",
    description: "大学の産学連携データを、年度・機関ごとに比較するWebツール。",
    role: "企画・開発",
    year: "2026",
    image: "/redesign/viewer-detail.png",
    width: 1440,
    height: 950,
    mobile: { image: "/redesign/viewer-mobile.png", width: 576, height: 398 },
    alt: "産連調査Viewer。3つの大学の共同研究・受託研究などを比較する実際のレーダーチャート",
    href: "https://unifactbook.pages.dev/",
    action: "ツールを使う",
  },
  {
    id: "governance",
    name: "大学職員のための生成AI最前線",
    description:
      "AIエージェントの実践から、大学組織のガバナンスを考える公開講演。",
    role: "講演・資料制作",
    year: "2026",
    image: "/redesign/governance-detail.jpg",
    width: 1920,
    height: 1080,
    mobile: null,
    alt: "公開講演資料の一頁。委任、守る、残す、振り返る、戻すの5つのフェーズと、組織で支える3つの要素",
    href: "https://speakerdeck.com/gmoriki/da-xue-zhi-yuan-notamenosheng-cheng-aizui-qian-xian-zui-qian-xian-wo-aigabanansutositedu-mizhi-sutamenotips",
    action: "講演資料を読む",
  },
  {
    id: "p4us",
    name: "P4Us",
    description:
      "大学の実務から、AIエージェントへの任せ方までを扱う公開ガイド。",
    role: "企画・開発・継続公開",
    year: "",
    image: "/redesign/p4us.png",
    width: 1440,
    height: 1000,
    mobile: { image: "/redesign/p4us-mobile.png", width: 522, height: 329 },
    alt: "P4Usの公開教材。会議準備をAIに任せる際の、目標・材料・境界・確認ポイントを示した実践例",
    href: "https://promptforus.com/docs/intermediate/advanced-use/agent-task-design/",
    action: "ガイドを読む",
  },
];
